### ISSUE TITLE
Unexpected exception in the selector loop. java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by vikashsingh009** [wwrd/ikvm8#7]
I  have  used  rocketmq 4.5  bin  put  lib  in  IKVM  build  and  started 2  console  Application  in  C#  ,Producer  Prodeces  successfully  but  after  some  time  getting   this  Error  in  rocketmq client  logs  and  Consumer  Stops Responding ..

WARN io.netty.channel.nio.NioEventLoop - Unexpected exception in the selector loop.
java.lang.ArrayIndexOutOfBoundsException
	at io.netty.util.internal.shaded.org.jctools.util.UnsafeRefArrayAccess.lvElement(UnsafeRefArrayAccess.java:94)
	at io.netty.util.internal.shaded.org.jctools.queues.MpscChunkedArrayQueue.poll(MpscChunkedArrayQueue.java:244)
	at io.netty.util.concurrent.SingleThreadEventExecutor.pollTask(SingleThreadEventExecutor.java:227)
	at io.netty.channel.nio.NioEventLoop.pollTask(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:424)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:455)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:141)
	at java.lang.Thread.run(Thread.java:955)

ERROR io.netty.util.concurrent.DefaultPromise.rejectedExecution - Failed to submit a listener notification task. Event loop shut down?
java.lang.ArrayIndexOutOfBoundsException
	at io.netty.util.internal.shaded.org.jctools.util.UnsafeRefArrayAccess.soElement(UnsafeRefArrayAccess.java:70)
	at io.netty.util.internal.shaded.org.jctools.queues.MpscChunkedArrayQueue.offer(MpscChunkedArrayQueue.java:194)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:347)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:338)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:748)
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:767)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:441)
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:121)
	at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:1004)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:831)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:730)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:743)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:735)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:820)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:730)
	at io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:743)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:735)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:820)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:107)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:743)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:735)
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:36)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1073)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1127)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1061)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:42)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:141)
	at java.lang.Thread.run(Thread.java:955)

**Comment by ghost** [comment]
I don't think that's an IKVM error. I think it's a netty error.

However, if you do find it's an IKVM error, please branch and fix and then create a PR and we'll review it and add it.

thanks - dave

**Comment by vikashsingh009** [comment]
I found similar issue herehttps://
sourceforge.net/p/ikvm/mailman/message/35520859/
